/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.SQLException;
import org.databene.jdbacl.dialect.FirebirdDialect;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBSequence;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestFirebirdDialect {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      FirebirdDialect firebirdDialect0 = null;
      try {
        firebirdDialect0 = new FirebirdDialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }
}
