/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.dialect.Derby10_6Dialect;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBSequence;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDerby10_6Dialect {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Derby10_6Dialect derby10_6Dialect0 = new Derby10_6Dialect();
      derby10_6Dialect0.sequenceNoCycle();
  }

  @Test
  public void test1()  throws Throwable  {
      Derby10_6Dialect derby10_6Dialect0 = new Derby10_6Dialect();
      String string0 = derby10_6Dialect0.renderFetchSequenceValue("'Rx[Ci`");
      assertEquals("VALUES (NEXT VALUE FOR 'Rx[Ci`)", string0);
      assertNotNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      Derby10_6Dialect derby10_6Dialect0 = new Derby10_6Dialect();
      DBSequence dBSequence0 = new DBSequence("zi", "zi", "zi");
      String string0 = derby10_6Dialect0.renderCreateSequence(dBSequence0);
      assertEquals("CREATE SEQUENCE zi.zi AS BIGINT", string0);
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      Derby10_6Dialect derby10_6Dialect0 = new Derby10_6Dialect();
      String string0 = derby10_6Dialect0.renderDropSequence("'Rx[Ci`");
      assertNotNull(string0);
      assertEquals("DROP SEQUENCE 'Rx[Ci` RESTRICT", string0);
  }

  @Test
  public void test4()  throws Throwable  {
      Derby10_6Dialect derby10_6Dialect0 = new Derby10_6Dialect();
      DBSequence dBSequence0 = new DBSequence("'Rx[Ci`", (DBSchema) null);
      String string0 = derby10_6Dialect0.renderCreateSequence(dBSequence0);
      assertEquals("CREATE SEQUENCE 'Rx[Ci` AS BIGINT", string0);
      assertNotNull(string0);
  }
}
