/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.dialect.UnknownDialect;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestUnknownDialect {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect("S)EoJG3bk&ZjI@");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect("|10");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      UnknownDialect unknownDialect0 = null;
      try {
        unknownDialect0 = new UnknownDialect("S)EoJG3bk&ZjI@");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }
}
