/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.databene.jdbacl.dialect.OracleDialect;
import org.databene.jdbacl.model.DBCatalog;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBSequence;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestOracleDialect {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      Timestamp timestamp0 = new Timestamp((-1L));
      oracleDialect0.formatTimestamp(timestamp0);
  }

  @Test
  public void test1()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      String string0 = oracleDialect0.renderFetchSequenceValue("s");
      assertEquals("select s.nextval from dual", string0);
      assertNotNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.supportsRegex();
      assertEquals(true, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDefaultSchema("du5}f0>f#vdv", "du5}f0>f#vdv");
      assertEquals(true, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDefaultCatalog("s", "s");
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDefaultCatalog((String) null, (String) null);
      assertEquals(true, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      DBSequence dBSequence0 = new DBSequence("", (DBSchema) null);
      String string0 = oracleDialect0.renderCreateSequence(dBSequence0);
      assertEquals("CREATE SEQUENCE \"\"", string0);
      assertNotNull(string0);
  }

  @Test
  public void test7()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      DBSequence dBSequence0 = new DBSequence("{b>#Pub579od", "{b>#Pub579od", "{b>#Pub579od");
      Long long0 = new Long((-367L));
      dBSequence0.setCache(long0);
      String string0 = oracleDialect0.renderCreateSequence(dBSequence0);
      assertNotNull(string0);
      assertEquals("CREATE SEQUENCE \"{b>#Pub579od\".\"{b>#Pub579od\" CACHE -367", string0);
  }

  @Test
  public void test8()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicCheckName("SYS_C00000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicCheckName("oracle");
      assertEquals(true, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicPKName("SYS_C00000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicPKName("s");
      assertEquals(true, boolean0);
  }

  @Test
  public void test12()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicUKName("SYS_C00000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicUKName("NOT REGEXP_LIKE(s, 's')");
      assertEquals(true, boolean0);
  }

  @Test
  public void test14()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicFKName("SYS_C00000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test15()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicFKName("NOT REGEXP_LIKE(s, 's')");
      assertEquals(true, boolean0);
  }

  @Test
  public void test16()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicIndexName("SYS_C00000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test17()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      boolean boolean0 = oracleDialect0.isDeterministicIndexName("du5}f0>f#vdv");
      assertEquals(true, boolean0);
  }

  @Test
  public void test18()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      String string0 = oracleDialect0.regexQuery("oracle", false, "oracle");
      assertNotNull(string0);
      assertEquals("REGEXP_LIKE(oracle, 'oracle')", string0);
  }

  @Test
  public void test19()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      String string0 = oracleDialect0.regexQuery("s", true, "s");
      assertEquals("NOT REGEXP_LIKE(s, 's')", string0);
      assertNotNull(string0);
  }

  @Test
  public void test20()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      // Undeclared exception!
      try {
        oracleDialect0.queryTriggers((DBSchema) null, (Connection) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test21()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      DBSchema dBSchema0 = new DBSchema("d");
      // Undeclared exception!
      try {
        oracleDialect0.queryTriggers(dBSchema0, (Connection) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test22()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      // Undeclared exception!
      try {
        oracleDialect0.queryPackages((DBSchema) null, (Connection) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test23()  throws Throwable  {
      OracleDialect oracleDialect0 = new OracleDialect();
      DBCatalog dBCatalog0 = new DBCatalog();
      DBSchema dBSchema0 = new DBSchema("SYS_C00000000", dBCatalog0);
      // Undeclared exception!
      try {
        oracleDialect0.queryPackages(dBSchema0, (Connection) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
