/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.SQLException;
import org.databene.commons.ConnectFailedException;
import org.databene.jdbacl.dialect.HSQLUtil;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestHSQLUtil {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      try {
        HSQLUtil.shutdown("|LySm}+0/Tr-|(", "|LySm}+0/Tr-|(", "g7 |9>:;eYK1");
        fail("Expecting exception: SQLException");
      } catch(SQLException e) {
        /*
         * No suitable driver found for |LySm}+0/Tr-|(
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      HSQLUtil.connectInMemoryDB("", 0);
  }

  @Test
  public void test2()  throws Throwable  {
      HSQLUtil hSQLUtil0 = new HSQLUtil();
      assertNotNull(hSQLUtil0);
  }
}
