/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.dialect;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.dialect.DerbyDialect;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDerbyDialect {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      derbyDialect0.isDefaultSchema("C~_9C", "C~_9C");
  }

  @Test
  public void test1()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect(false);
      boolean boolean0 = derbyDialect0.isDefaultCatalog("1loo=^',+a+0z5zd", "1loo=^',+a+0z5zd");
      assertEquals(true, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect(false);
      boolean boolean0 = derbyDialect0.isDefaultSchema("app", "app");
      assertEquals(true, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDefaultSchema("h!=%3_3;^s>;", "S!oIdVtZn08LD8");
      assertEquals(false, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicPKName("SQL000000000000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicPKName("S!oIdVtZn08LD8");
      assertEquals(true, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect(false);
      boolean boolean0 = derbyDialect0.isDeterministicUKName("SQL000000000000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicUKName("FK000000000000000");
      assertEquals(true, boolean0);
  }

  @Test
  public void test8()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicFKName("FK000000000000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect(false);
      boolean boolean0 = derbyDialect0.isDeterministicFKName("SQL000000000000000");
      assertEquals(true, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicIndexName("SQL000000000000000");
      assertEquals(false, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      DerbyDialect derbyDialect0 = new DerbyDialect();
      boolean boolean0 = derbyDialect0.isDeterministicIndexName("h!=%3_3;^s>;");
      assertEquals(true, boolean0);
  }
}
