/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model.jdbc;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.sql.SQLException;
import org.databene.jdbacl.JDBCConnectData;
import org.databene.jdbacl.model.CompositeDBObject;
import org.databene.jdbacl.model.DBCatalog;
import org.databene.jdbacl.model.DBCheckConstraint;
import org.databene.jdbacl.model.DBColumn;
import org.databene.jdbacl.model.DBForeignKeyConstraint;
import org.databene.jdbacl.model.DBIndex;
import org.databene.jdbacl.model.DBObject;
import org.databene.jdbacl.model.DBPrimaryKeyConstraint;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DBUniqueConstraint;
import org.databene.jdbacl.model.jdbc.JDBCDBImporter;
import org.databene.jdbacl.model.jdbc.LazyTable;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLazyTable {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, (DBSchema) null, "&16nhZ5", "&16nhZ5");
      // Undeclared exception!
      try {
        lazyTable0.getForeignKeyConstraints();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("v", "v", "v", "v", "v", "v", "v", false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      DBSchema dBSchema0 = new DBSchema("");
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, dBSchema0, "", "");
      // Undeclared exception!
      try {
        lazyTable0.isIdentical((DBObject) dBSchema0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("!$`Q9`{L}", "!$`Q9`{L}", "!$`Q9`{L}", "!$`Q9`{L}", ">_Lyw+5V]vl", ">_Lyw+5V]vl");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, (DBSchema) null, "java.vendor", "java.vendor");
      // Undeclared exception!
      try {
        lazyTable0.addColumn((DBColumn) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("", "", "", "", "", "", "", true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("P3;s+5)8,\"Yg", "P3;s+5)8,\"Yg", "P3;s+5)8,\"Yg", "P3;s+5)8,\"Yg", "P3;s+5)8,\"Yg", "P3;s+5)8,\"Yg");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, (DBSchema) null, "", "");
      // Undeclared exception!
      try {
        lazyTable0.getUniqueConstraints(false);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test9()  throws Throwable  {
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, (DBSchema) null, "hmaRv+YIxX", "hmaRv+YIxX");
      // Undeclared exception!
      try {
        lazyTable0.getOwner();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test10()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("F:ASA#i^", "F:ASA#i^", "F:ASA#i^", "F:ASA#i^", "F:ASA#i^", "F:ASA#i^");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("B` K-y/|T$$p.EDOq", "KWXbSR%=[v>AXG6", "KWXbSR%=[v>AXG6", "KWXbSR%=[v>AXG6", "KWXbSR%=[v>AXG6", "B` K-y/|T$$p.EDOq");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("F6^=zRV7lt=?hQE{A-", "F6^=zRV7lt=?hQE{A-", "F6^=zRV7lt=?hQE{A-", "F6^=zRV7lt=?hQE{A-", "F6^=zRV7lt=?hQE{A-", "F6^=zRV7lt=?hQE{A-");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      DBSchema dBSchema0 = new DBSchema("@E^=}edXD!+x-*", (DBCatalog) null);
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, dBSchema0, "@E^=}edXD!+x-*", "@E^=}edXD!+x-*");
      // Undeclared exception!
      try {
        lazyTable0.getReferrers();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test15()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("v", "v", "v", "v", "v", "v", "v", false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", "4y-S!_-llF7w4t$", true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, "SYSTEM_PROCEDURECOLUMNS");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      DBSchema dBSchema0 = new DBSchema("N5Hk\u0007~\"S*(pZ.u'i");
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, dBSchema0, "N5Hk\u0007~\"S*(pZ.u'i", "N5Hk\u0007~\"S*(pZ.u'i");
      // Undeclared exception!
      try {
        lazyTable0.getPrimaryKeyConstraint();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test20()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((Connection) null, "ID:eJD", "ID:eJD");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test21()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("^", "^", "^", "^", "^", "^");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test22()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, "SYSTEM_PROCEDURECOLUMNS");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test23()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("7cw?Z+Kx?M H%yIJ{", "7cw?Z+Kx?M H%yIJ{", "7cw?Z+Kx?M H%yIJ{", "7cw?Z+Kx?M H%yIJ{");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test25()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((Connection) null, "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test26()  throws Throwable  {
      LazyTable lazyTable0 = new LazyTable((JDBCDBImporter) null, (DBSchema) null, "", "");
      // Undeclared exception!
      try {
        lazyTable0.addIndex((DBIndex) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test27()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("Ny]sAmm", "Ny]sAmm", "Ny]sAmm", "Ny]sAmm", "Ny]sAmm", "Ny]sAmm", "tXd~kpU", false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test28()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test29()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("", "", "`*'aaX&iI", "`*'aaX&iI", "`*'aaX&iI", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test30()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test31()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("i#Om", "i#Om", "i#Om", "i#Om");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test32()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("", "", "", "", "", "");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test33()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test34()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("r`:Bi;Os=Ls", "r`:Bi;Os=Ls", "r`:Bi;Os=Ls", "r`:Bi;Os=Ls", "r`:Bi;Os=Ls", "r`:Bi;Os=Ls");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test35()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("", "", "", "", "(sHXrqz&dZ?9{j^Y]", "(sHXrqz&dZ?9{j^Y]");
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(jDBCConnectData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test36()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", "0P85n?0J*00U1%ah#n`", true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test37()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter("", "", "", "", "", "", "", true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test38()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter(",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", ",C/`p5?<C,0#u", false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test39()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, "SYSTEM_PROCEDURECOLUMNS");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }

  @Test
  public void test40()  throws Throwable  {
      JDBCDBImporter jDBCDBImporter0 = null;
      try {
        jDBCDBImporter0 = new JDBCDBImporter((String) null, (String) null, (String) null, (String) null, (String) null, "SYSTEM_PROCEDURECOLUMNS");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.jdbc.JDBCDBImporter
         */
      }
  }
}
