/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model.xml;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.IOException;
import org.apache.html.dom.HTMLDocumentImpl;
import org.apache.html.dom.HTMLElementImpl;
import org.databene.commons.ImportFailedException;
import org.databene.jdbacl.model.xml.XMLModelImporter;
import org.junit.BeforeClass;
import org.w3c.dom.Element;

@RunWith(EvoSuiteRunner.class)
public class TestXMLModelImporter {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XMLModelImporter xMLModelImporter0 = null;
      try {
        xMLModelImporter0 = new XMLModelImporter((File) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.xml.XMLModelImporter
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("=", "=");
      XMLModelImporter xMLModelImporter0 = null;
      try {
        xMLModelImporter0 = new XMLModelImporter(file0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.xml.XMLModelImporter
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      File file0 = new File("");
      XMLModelImporter xMLModelImporter0 = null;
      try {
        xMLModelImporter0 = new XMLModelImporter(file0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.xml.XMLModelImporter
         */
      }
  }
}
