/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.sql.SQLException;
import javax.sql.ConnectionEventListener;
import javax.sql.ConnectionPoolDataSource;
import org.databene.jdbacl.proxy.PooledConnectionHandler;
import org.h2.jdbcx.JdbcConnectionPool;
import org.h2.jdbcx.JdbcDataSource;
import org.hsqldb.HsqlException;
import org.hsqldb.Session;
import org.hsqldb.jdbc.jdbcConnection;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestPooledConnectionHandler {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PooledConnectionHandler pooledConnectionHandler0 = new PooledConnectionHandler((Connection) null, true);
      JdbcDataSource jdbcDataSource0 = new JdbcDataSource();
      JdbcConnectionPool jdbcConnectionPool0 = JdbcConnectionPool.create((ConnectionPoolDataSource) jdbcDataSource0);
      pooledConnectionHandler0.removeConnectionEventListener((ConnectionEventListener) jdbcConnectionPool0);
  }

  @Test
  public void test1()  throws Throwable  {
      PooledConnectionHandler pooledConnectionHandler0 = new PooledConnectionHandler((Connection) null, true);
      assertNotNull(pooledConnectionHandler0);
      
      JdbcDataSource jdbcDataSource0 = new JdbcDataSource();
      JdbcConnectionPool jdbcConnectionPool0 = JdbcConnectionPool.create((ConnectionPoolDataSource) jdbcDataSource0);
      pooledConnectionHandler0.addConnectionEventListener((ConnectionEventListener) jdbcConnectionPool0);
      assertEquals(2, pooledConnectionHandler0.getOpenConnectionCount());
      assertEquals(0, jdbcDataSource0.getTraceId());
  }

  @Test
  public void test2()  throws Throwable  {
      jdbcConnection jdbcConnection0 = new jdbcConnection((Session) null);
      PooledConnectionHandler pooledConnectionHandler0 = new PooledConnectionHandler((Connection) jdbcConnection0, true);
      assertNotNull(pooledConnectionHandler0);
      
      pooledConnectionHandler0.getConnection();
      assertEquals(29, pooledConnectionHandler0.getOpenConnectionCount());
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        PooledConnectionHandler.assertAllConnectionsClosed(false);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      int int0 = PooledConnectionHandler.getOpenConnectionCount();
      assertEquals(54, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      jdbcConnection jdbcConnection0 = new jdbcConnection((Session) null);
      PooledConnectionHandler pooledConnectionHandler0 = new PooledConnectionHandler((Connection) jdbcConnection0, true);
      assertNotNull(pooledConnectionHandler0);
      assertEquals(55, pooledConnectionHandler0.getOpenConnectionCount());
      
      pooledConnectionHandler0.close();
      pooledConnectionHandler0.close();
      assertEquals(54, pooledConnectionHandler0.getOpenConnectionCount());
  }

  @Test
  public void test6()  throws Throwable  {
      PooledConnectionHandler.resetMonitors();
  }
}
