/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.proxy;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.databene.jdbacl.proxy.LoggingPreparedStatementHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLoggingPreparedStatementHandler {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "\"OZy");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "*/if/else");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "releaseIkpl(): no action: reurningLtrue");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "loclEncodin");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "TkEXP");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "zeaf_T}N*BW_");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "getHoldability()");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "*/if/else");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try {
        LoggingPreparedStatementHandler.assertAllStatementsClosed(false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "*/if//then");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try {
        LoggingPreparedStatementHandler.getOpenStatementCount();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "^0OM.9uHUm>)AH4'l");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "6X(_u1RM|PZmZzX");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "- lSV(g`kIN");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "OU{L4t;S/B,~7S{>#l");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "readStatusVector arg: ");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test17()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "9gER");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test18()  throws Throwable  {
      LoggingPreparedStatementHandler loggingPreparedStatementHandler0 = null;
      try {
        loggingPreparedStatementHandler0 = new LoggingPreparedStatementHandler((PreparedStatement) null, "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }

  @Test
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try {
        LoggingPreparedStatementHandler.resetMonitors();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.proxy.LoggingPreparedStatementHandler
         */
      }
  }
}
