/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.identity.SimpleTranscoder;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSimpleTranscoder {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleTranscoder simpleTranscoder0 = new SimpleTranscoder();
      assertNotNull(simpleTranscoder0);
  }
}
