/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.commons.version.VersionNumber;
import org.databene.jdbacl.identity.IdentityProvider;
import org.databene.jdbacl.identity.mem.MemKeyMapper;
import org.databene.jdbacl.model.Database;
import org.databene.jdbacl.model.DefaultDatabase;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestKeyMapper {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IdentityProvider identityProvider0 = new IdentityProvider();
      VersionNumber versionNumber0 = VersionNumber.valueOf("}2Ye[Vk}4Nh");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("}2Ye[Vk}4Nh", "}2Ye[Vk}4Nh", versionNumber0);
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "}2Ye[Vk}4Nh", (Connection) null, "}2Ye[Vk}4Nh", identityProvider0, (Database) defaultDatabase0);
      IdentityProvider identityProvider1 = memKeyMapper0.getIdentityProvider();
      assertSame(identityProvider0, identityProvider1);
  }
}
