/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.commons.AssertionError;
import org.databene.jdbacl.identity.IdentityProvider;
import org.databene.jdbacl.identity.KeyMapper;
import org.databene.jdbacl.identity.NkPkQueryIdentity;
import org.databene.jdbacl.identity.mem.MemKeyMapper;
import org.databene.jdbacl.model.Database;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestNkPkQueryIdentity {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NkPkQueryIdentity nkPkQueryIdentity0 = new NkPkQueryIdentity("localhost", "localhost");
      nkPkQueryIdentity0.getDescription();
  }

  @Test
  public void test1()  throws Throwable  {
      NkPkQueryIdentity nkPkQueryIdentity0 = new NkPkQueryIdentity("", "");
      IdentityProvider identityProvider0 = new IdentityProvider();
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "", (Connection) null, "", identityProvider0, (Database) null);
      // Undeclared exception!
      try {
        nkPkQueryIdentity0.createNkPkIterator((Connection) null, "", (KeyMapper) memKeyMapper0, (Database) null);
        fail("Expecting exception: AssertionError");
      } catch(AssertionError e) {
        /*
         * query
         */
      }
  }
}
