/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.sql;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.CharArrayReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.io.StringReader;
import org.antlr.runtime.ANTLRInputStream;
import org.antlr.runtime.ANTLRReaderStream;
import org.antlr.runtime.ANTLRStringStream;
import org.antlr.runtime.CharStream;
import org.databene.commons.ParseException;
import org.databene.jdbacl.DatabaseDialect;
import org.databene.jdbacl.dialect.DerbyDialect;
import org.databene.jdbacl.dialect.Firebird2_5Dialect;
import org.databene.jdbacl.dialect.H2Dialect;
import org.databene.jdbacl.sql.SQLParserUtil;
import org.databene.jdbacl.sql.parser.ANTLRNoCaseStringStream;
import org.h2.value.ValueShort;
import org.hsqldb.rowio.RowInputBinary;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSQLParserUtil {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ANTLRStringStream aNTLRStringStream0 = new ANTLRStringStream("'/l'.7;?77(M+");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ANTLRStringStream aNTLRStringStream0 = new ANTLRStringStream("#gX}gjPQQFNuOb");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      SQLParserUtil sQLParserUtil0 = null;
      try {
        sQLParserUtil0 = new SQLParserUtil();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ANTLRStringStream aNTLRStringStream0 = new ANTLRStringStream("k=_0B)IV%Ocu>YT");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ValueShort valueShort0 = ValueShort.get((short) (-20));
      StringReader stringReader0 = (StringReader)valueShort0.getReader();
      ANTLRReaderStream aNTLRReaderStream0 = new ANTLRReaderStream((Reader) stringReader0, (int) (short) (-20));
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRReaderStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("jKQk<ULy");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRNoCaseStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("i-o+KbR");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRNoCaseStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("registerOutParameter(int,int,String)");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRNoCaseStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      ANTLRInputStream aNTLRInputStream0 = new ANTLRInputStream();
      DerbyDialect derbyDialect0 = null;
      try {
        derbyDialect0 = new DerbyDialect(true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("Z");
      Firebird2_5Dialect firebird2_5Dialect0 = null;
      try {
        firebird2_5Dialect0 = new Firebird2_5Dialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      RowInputBinary rowInputBinary0 = new RowInputBinary();
      ANTLRInputStream aNTLRInputStream0 = new ANTLRInputStream((InputStream) rowInputBinary0);
      H2Dialect h2Dialect0 = null;
      try {
        h2Dialect0 = new H2Dialect();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * ch/qos/logback/classic/util/LoggerNameUtil
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("5vF#-JhO!R/(8r<8");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRNoCaseStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      char[] charArray0 = new char[4];
      charArray0[0] = 'm';
      charArray0[1] = 'm';
      charArray0[2] = '/';
      charArray0[3] = 'm';
      CharArrayReader charArrayReader0 = new CharArrayReader(charArray0);
      ANTLRReaderStream aNTLRReaderStream0 = new ANTLRReaderStream((Reader) charArrayReader0);
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRReaderStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      ANTLRNoCaseStringStream aNTLRNoCaseStringStream0 = new ANTLRNoCaseStringStream("'/l'.7;?77(M+");
      // Undeclared exception!
      try {
        SQLParserUtil.parseExpression((CharStream) aNTLRNoCaseStringStream0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.sql.SQLParserUtil
         */
      }
  }
}
