/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.sql;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.sql.ColumnExpression;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestColumnExpression {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ColumnExpression columnExpression0 = new ColumnExpression("", true);
      String string0 = columnExpression0.getColumnName();
      assertNotNull(string0);
      assertEquals(true, columnExpression0.isQuoted());
  }

  @Test
  public void test1()  throws Throwable  {
      ColumnExpression columnExpression0 = new ColumnExpression("OXjZ5@g.", true);
      boolean boolean0 = columnExpression0.isQuoted();
      assertEquals(true, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      ColumnExpression columnExpression0 = new ColumnExpression("OXjZ5@g.", false);
      String string0 = columnExpression0.toString();
      assertNotNull(string0);
      assertEquals("OXjZ5@g.", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      ColumnExpression columnExpression0 = new ColumnExpression("OXjZ5@g.", true);
      String string0 = columnExpression0.toString();
      assertNotNull(string0);
      assertEquals("\"OXjZ5@g.\"", string0);
      assertEquals(true, columnExpression0.isQuoted());
  }
}
