/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity.xml;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.identity.xml.IdentityParseContext;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestIdentityParseContext {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IdentityParseContext identityParseContext0 = new IdentityParseContext();
      identityParseContext0.getIdentityProvider();
  }
}
