/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.commons.version.VersionNumber;
import org.databene.jdbacl.DatabaseTreeModel;
import org.databene.jdbacl.model.DBObject;
import org.databene.jdbacl.model.Database;
import org.databene.jdbacl.model.DefaultDatabase;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseTreeModel {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) null);
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("", "", (VersionNumber) null);
      DBObject dBObject0 = databaseTreeModel0.getParent((DBObject) defaultDatabase0);
      assertNull(dBObject0);
  }

  @Test
  public void test1()  throws Throwable  {
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) null);
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("", "", (VersionNumber) null);
      int int0 = databaseTreeModel0.getChildCount((DBObject) defaultDatabase0);
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf(",I-JB|&vgg/");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase(",I-JB|&vgg/", ",I-JB|&vgg/", versionNumber0);
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) defaultDatabase0);
      int int0 = databaseTreeModel0.getIndexOfChild((DBObject) defaultDatabase0, (DBObject) defaultDatabase0);
      assertEquals((-1), int0);
  }

  @Test
  public void test3()  throws Throwable  {
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) null);
      DBObject dBObject0 = (DBObject)databaseTreeModel0.getRoot();
      assertNull(dBObject0);
  }

  @Test
  public void test4()  throws Throwable  {
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) null);
      // Undeclared exception!
      try {
        databaseTreeModel0.getChild((DBObject) null, 1422);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("not null constraint", "not null constraint", (VersionNumber) null);
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) defaultDatabase0);
      boolean boolean0 = databaseTreeModel0.isLeaf((DBObject) defaultDatabase0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      DatabaseTreeModel databaseTreeModel0 = new DatabaseTreeModel((Database) null);
      boolean boolean0 = databaseTreeModel0.isLeaf((DBObject) null);
      assertEquals(true, boolean0);
  }
}
