/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.jdbacl.QueryIterator;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestQueryIterator {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      QueryIterator queryIterator0 = null;
      try {
        queryIterator0 = new QueryIterator("vvppU^`9`}~F_UW\"rXx", (Connection) null, 1890);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
