/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.ResultSet;
import org.databene.jdbacl.ResultSetIterator;
import org.h2.tools.Csv;
import org.h2.tools.SimpleResultSet;
import org.h2.tools.SimpleRowSource;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestResultSetIterator {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0, "B*5A1e$d2uyF");
      resultSetIterator0.toString();
  }

  @Test
  public void test1()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0);
      resultSetIterator0.getColumnLabels();
      resultSetIterator0.getColumnLabels();
  }

  @Test
  public void test2()  throws Throwable  {
      Csv csv0 = Csv.getInstance();
      SimpleResultSet simpleResultSet0 = new SimpleResultSet((SimpleRowSource) csv0);
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0, "");
      // Undeclared exception!
      try {
        resultSetIterator0.remove();
        fail("Expecting exception: UnsupportedOperationException");
      } catch(UnsupportedOperationException e) {
        /*
         * Not supported
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ResultSetIterator resultSetIterator0 = null;
      try {
        resultSetIterator0 = new ResultSetIterator((ResultSet) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * resultSet is null
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      simpleResultSet0.addColumn("", 1329, 1329, 1329);
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0);
      resultSetIterator0.getColumnLabels();
  }

  @Test
  public void test5()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0);
      assertNotNull(resultSetIterator0);
      
      resultSetIterator0.hasNext();
      // Undeclared exception!
      try {
        resultSetIterator0.next();
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
        /*
         * No more row available. Use hasNext() for checking availability.
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      Object[] objectArray0 = new Object[12];
      simpleResultSet0.addRow(objectArray0);
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0, "B*5A1e$d2uyF");
      resultSetIterator0.next();
  }

  @Test
  public void test7()  throws Throwable  {
      SimpleResultSet simpleResultSet0 = new SimpleResultSet();
      ResultSetIterator resultSetIterator0 = new ResultSetIterator((ResultSet) simpleResultSet0);
      assertNotNull(resultSetIterator0);
      
      boolean boolean0 = resultSetIterator0.hasNext();
      assertEquals(false, boolean0);
      
      resultSetIterator0.close();
      assertEquals("ResultSetIterator[]", resultSetIterator0.toString());
  }
}
