/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.commons.version.VersionNumber;
import org.databene.jdbacl.DatabaseDialectManager;
import org.databene.jdbacl.dialect.HSQL2Dialect;
import org.databene.jdbacl.dialect.HSQLDialect;
import org.databene.jdbacl.dialect.UnknownDialect;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDatabaseDialectManager {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabaseDialectManager databaseDialectManager0 = new DatabaseDialectManager();
  }

  @Test
  public void test1()  throws Throwable  {
      UnknownDialect unknownDialect0 = (UnknownDialect)DatabaseDialectManager.getDialectForProduct("@O>6 nxSS}(8,+f", (VersionNumber) null);
      assertEquals("@O>6 nxSS}(8,+f", unknownDialect0.getSystem());
  }

  @Test
  public void test2()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("hsqlN:iYgnl_eisio`");
      HSQLDialect hSQLDialect0 = (HSQLDialect)DatabaseDialectManager.getDialectForProduct("hsqlN:iYgnl_eisio`", versionNumber0);
      assertEquals(false, hSQLDialect0.supportsRegex());
  }

  @Test
  public void test3()  throws Throwable  {
      HSQL2Dialect hSQL2Dialect0 = (HSQL2Dialect)DatabaseDialectManager.getDialectForProduct("hsqlN:iYgnl_eisio`", (VersionNumber) null);
      assertEquals(true, hSQL2Dialect0.isSequenceBoundarySupported());
  }
}
