/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model.cache;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.IOException;
import org.databene.commons.ConnectFailedException;
import org.databene.commons.ImportFailedException;
import org.databene.jdbacl.model.DBMetaDataImporter;
import org.databene.jdbacl.model.cache.CachingDBImporter;
import org.databene.jdbacl.model.xml.XMLModelImporter;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestCachingDBImporter {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        CachingDBImporter.getCacheFile("QQn");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.cache.CachingDBImporter
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      CachingDBImporter cachingDBImporter0 = null;
      try {
        cachingDBImporter0 = new CachingDBImporter((DBMetaDataImporter) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.cache.CachingDBImporter
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      CachingDBImporter cachingDBImporter0 = null;
      try {
        cachingDBImporter0 = new CachingDBImporter((DBMetaDataImporter) null, (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.cache.CachingDBImporter
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        CachingDBImporter.getCacheFile("QQn");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.databene.jdbacl.model.cache.CachingDBImporter
         */
      }
  }
}
