/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.version;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.commons.version.VersionNumber;
import org.databene.jdbacl.version.ConstantVersionProvider;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestConstantVersionProvider {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConstantVersionProvider constantVersionProvider0 = new ConstantVersionProvider((VersionNumber) null);
      VersionNumber versionNumber0 = constantVersionProvider0.getVersion((Connection) null);
      assertNull(versionNumber0);
  }
}
