/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity.mem;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.commons.bean.ObjectOrArray;
import org.databene.jdbacl.identity.mem.GlobalRowId;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGlobalRowId {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6");
      assertNotNull(globalRowId0);
      
      String string0 = globalRowId0.toString();
      assertEquals("V|'Nj-`V*k+-Y\"cjWA6.V|'Nj-`V*k+-Y\"cjWA6#V|'Nj-`V*k+-Y\"cjWA6", string0);
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("&g%", "&g%", "[\"HR:Yfyv/%q");
      assertNotNull(globalRowId0);
      
      int int0 = globalRowId0.hashCode();
      assertEquals(1500452232, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("&g%", "&g%", "[\"HR:Yfyv/%q");
      assertNotNull(globalRowId0);
      
      boolean boolean0 = globalRowId0.equals((Object) "&g%");
      assertEquals(false, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6");
      assertNotNull(globalRowId0);
      
      boolean boolean0 = globalRowId0.equals((Object) null);
      assertEquals(false, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("&g%", "&g%", "[\"HR:Yfyv/%q");
      assertNotNull(globalRowId0);
      
      GlobalRowId globalRowId1 = new GlobalRowId("&g%", "[\"HR:Yfyv/%q", (Object) globalRowId0);
      boolean boolean0 = globalRowId1.equals((Object) globalRowId0);
      assertEquals(false, boolean0);
      assertEquals("&g%.[\"HR:Yfyv/%q#&g%.&g%#[\"HR:Yfyv/%q", globalRowId1.toString());
  }

  @Test
  public void test5()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6");
      assertNotNull(globalRowId0);
      
      GlobalRowId globalRowId1 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6.V|'Nj-`V*k+-Y\"cjWA6#V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6.V|'Nj-`V*k+-Y\"cjWA6#V|'Nj-`V*k+-Y\"cjWA6", (Object) globalRowId0);
      boolean boolean0 = globalRowId0.equals((Object) globalRowId1);
      assertEquals(false, boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6");
      assertNotNull(globalRowId0);
      
      ObjectOrArray objectOrArray0 = new ObjectOrArray((Object) "V|'Nj-`V*k+-Y\"cjWA6");
      GlobalRowId globalRowId1 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", (Object) objectOrArray0);
      boolean boolean0 = globalRowId1.equals((Object) globalRowId0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      GlobalRowId globalRowId0 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6");
      assertNotNull(globalRowId0);
      
      GlobalRowId globalRowId1 = new GlobalRowId("V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6", "V|'Nj-`V*k+-Y\"cjWA6.V|'Nj-`V*k+-Y\"cjWA6#V|'Nj-`V*k+-Y\"cjWA6");
      boolean boolean0 = globalRowId0.equals((Object) globalRowId1);
      assertEquals(false, boolean0);
  }
}
