/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity.mem;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.jdbacl.identity.IdentityModel;
import org.databene.jdbacl.identity.IdentityProvider;
import org.databene.jdbacl.identity.KeyMapper;
import org.databene.jdbacl.identity.NaturalPkIdentity;
import org.databene.jdbacl.identity.NoIdentity;
import org.databene.jdbacl.identity.mem.MemKeyMapper;
import org.databene.jdbacl.identity.mem.SourceTableMapper;
import org.databene.jdbacl.identity.mem.TargetTableMapper;
import org.databene.jdbacl.model.Database;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractTableMapper {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "dx?|baseNnme", (Connection) null, "dx?|baseNnme", (IdentityProvider) null, (Database) null);
      NaturalPkIdentity naturalPkIdentity0 = new NaturalPkIdentity("dx?|baseNnme");
      TargetTableMapper targetTableMapper0 = new TargetTableMapper((KeyMapper) memKeyMapper0, (Connection) null, "dx?|baseNnme", (IdentityModel) naturalPkIdentity0, (Database) null);
      // Undeclared exception!
      try {
        targetTableMapper0.getNaturalKey((Object) "TABLE");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "dx?|baseNnme", (Connection) null, "dx?|baseNnme", (IdentityProvider) null, (Database) null);
      NoIdentity noIdentity0 = new NoIdentity("dx?|baseNnme");
      SourceTableMapper sourceTableMapper0 = new SourceTableMapper((KeyMapper) memKeyMapper0, (Connection) null, "dx?|baseNnme", (IdentityModel) noIdentity0, (Database) null);
      sourceTableMapper0.store((Object) "TABLE", "TABLE", (Object) "TABLE");
      sourceTableMapper0.store((Object) "dx?|baseNnme", "TABLE", (Object) "TABLE");
  }

  @Test
  public void test2()  throws Throwable  {
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "dx?|baseNnme", (Connection) null, "dx?|baseNnme", (IdentityProvider) null, (Database) null);
      NoIdentity noIdentity0 = new NoIdentity("dx?|baseNnme");
      SourceTableMapper sourceTableMapper0 = new SourceTableMapper((KeyMapper) memKeyMapper0, (Connection) null, "dx?|baseNnme", (IdentityModel) noIdentity0, (Database) null);
      sourceTableMapper0.store((Object) "TABLE", "TABLE", (Object) "TABLE");
      sourceTableMapper0.assureInitialized();
  }
}
