/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.identity.mem;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import org.databene.jdbacl.identity.IdentityModel;
import org.databene.jdbacl.identity.IdentityProvider;
import org.databene.jdbacl.identity.KeyMapper;
import org.databene.jdbacl.identity.NaturalPkIdentity;
import org.databene.jdbacl.identity.mem.MemKeyMapper;
import org.databene.jdbacl.identity.mem.SourceTableMapper;
import org.databene.jdbacl.model.Database;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSourceTableMapper {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IdentityProvider identityProvider0 = new IdentityProvider();
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "jY~}lif@O", (Connection) null, "jY~}lif@O", identityProvider0, (Database) null);
      NaturalPkIdentity naturalPkIdentity0 = new NaturalPkIdentity("jY~}lif@O");
      SourceTableMapper sourceTableMapper0 = new SourceTableMapper((KeyMapper) memKeyMapper0, (Connection) null, "jY~}lif@O", (IdentityModel) naturalPkIdentity0, (Database) null);
      // Undeclared exception!
      try {
        sourceTableMapper0.getTargetPK((Object) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      IdentityProvider identityProvider0 = new IdentityProvider();
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "jY~}lif@O", (Connection) null, "jY~}lif@O", identityProvider0, (Database) null);
      NaturalPkIdentity naturalPkIdentity0 = new NaturalPkIdentity("jY~}lif@O");
      memKeyMapper0.store("jY~}lif@O", (IdentityModel) naturalPkIdentity0, "jY~}lif@O", (Object) "393", (Object) null);
      assertEquals("NaturalPkIdentity(jY~}lif@O)", naturalPkIdentity0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      IdentityProvider identityProvider0 = new IdentityProvider();
      MemKeyMapper memKeyMapper0 = new MemKeyMapper((Connection) null, "jY~}lif@O", (Connection) null, "jY~}lif@O", identityProvider0, (Database) null);
      NaturalPkIdentity naturalPkIdentity0 = new NaturalPkIdentity("jY~}lif@O");
      memKeyMapper0.store("jY~}lif@O", (IdentityModel) naturalPkIdentity0, "jY~}lif@O", (Object) "ds471", (Object) "ds471");
      assertEquals("jY~}lif@O", naturalPkIdentity0.getTableName());
  }
}
