/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.model.DBObject;
import org.databene.jdbacl.model.DBPrimaryKeyConstraint;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DBUniqueConstraint;
import org.databene.jdbacl.model.DBUniqueIndex;
import org.databene.jdbacl.model.DefaultDBTable;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDBUniqueIndex {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable();
      String[] stringArray0 = new String[21];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, (String) null, false, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex((String) null, false, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      int int0 = dBUniqueIndex0.hashCode();
      assertEquals((-2038056289), int0);
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable();
      String[] stringArray0 = new String[21];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, (String) null, false, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex((String) null, false, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      boolean boolean0 = dBUniqueIndex0.isUnique();
      assertEquals(true, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable();
      String[] stringArray0 = new String[21];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, (String) null, false, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex((String) null, false, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      DefaultDBTable defaultDBTable1 = (DefaultDBTable)dBUniqueIndex0.getTable();
      assertNull(defaultDBTable1.getName());
  }

  @Test
  public void test3()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable((String) null);
      String[] stringArray0 = new String[8];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, (String) null, true, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex((String) null, true, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      dBUniqueIndex0.addColumnName((String) null);
      assertNull(dBUniqueIndex0.getDoc());
  }

  @Test
  public void test4()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable("I7]wRFSOd4pWV+1+:l");
      String[] stringArray0 = new String[6];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, "I7]wRFSOd4pWV+1+:l", true, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex("I7]wRFSOd4pWV+1+:l", true, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      boolean boolean0 = dBUniqueIndex0.isIdentical((DBObject) null);
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable("I7]wRFSOd4pWV+1+:l");
      String[] stringArray0 = new String[6];
      DBPrimaryKeyConstraint dBPrimaryKeyConstraint0 = new DBPrimaryKeyConstraint((DBTable) defaultDBTable0, "I7]wRFSOd4pWV+1+:l", true, stringArray0);
      DBUniqueIndex dBUniqueIndex0 = new DBUniqueIndex("I7]wRFSOd4pWV+1+:l", true, (DBUniqueConstraint) dBPrimaryKeyConstraint0);
      boolean boolean0 = dBUniqueIndex0.isIdentical((DBObject) dBPrimaryKeyConstraint0);
      assertEquals(false, boolean0);
  }
}
