/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.sql.SQLException;
import org.databene.jdbacl.model.DBRowIterator;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DefaultDBTable;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDBRowIterator {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable();
      // Undeclared exception!
      try {
        defaultDBTable0.allRows((Connection) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable("http://www.slf4j.org/codes.html#null_LF");
      DBRowIterator dBRowIterator0 = null;
      try {
        dBRowIterator0 = new DBRowIterator((DBTable) defaultDBTable0, (Connection) null, "http://www.slf4j.org/codes.html#null_LF");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
