/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.model.DBDataType;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDBDataType {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1856, "DATE");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isTemporal();
      assertEquals(1856, dBDataType0.getJdbcType());
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      DBDataType.getInstance("S|VpHC^c");
  }

  @Test
  public void test2()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1298, "BLOB");
      assertNotNull(dBDataType0);
      
      int int0 = dBDataType0.getJdbcType();
      assertEquals(1298, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("BLOB");
      assertNotNull(dBDataType0);
      
      int int0 = dBDataType0.hashCode();
      assertEquals(2041757, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      String string0 = dBDataType0.getName();
      assertNotNull(string0);
      assertEquals(0, dBDataType0.getJdbcType());
      assertEquals(true, dBDataType0.isNumber());
  }

  @Test
  public void test5()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      String string0 = dBDataType0.toString();
      assertNotNull(string0);
      assertEquals(true, dBDataType0.isNumber());
      assertEquals(0, dBDataType0.getJdbcType());
  }

  @Test
  public void test6()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1432, "NVARCHAR2");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isNumber();
      assertEquals(true, boolean0);
  }

  @Test
  public void test7()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("BLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(true, boolean0);
  }

  @Test
  public void test8()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("CLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(true, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("NCLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(true, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance((-1323), "TIME");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(true, dBDataType0.isNumber());
      assertEquals(false, boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1196, "TIME06CLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(true, dBDataType0.isNumber());
      assertEquals(true, boolean0);
  }

  @Test
  public void test12()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1298, "BLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isLOB();
      assertEquals(1298, dBDataType0.getJdbcType());
      assertEquals(true, boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isAlpha();
      assertEquals(false, boolean0);
  }

  @Test
  public void test14()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance((-1), " t0N2");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isAlpha();
      assertEquals(true, boolean0);
  }

  @Test
  public void test15()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1432, "NVARCHAR2");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isAlpha();
      assertEquals(true, boolean0);
      assertEquals(1432, dBDataType0.getJdbcType());
  }

  @Test
  public void test16()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1196, "TIME06CLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isAlpha();
      assertEquals(true, boolean0);
      assertEquals(1196, dBDataType0.getJdbcType());
  }

  @Test
  public void test17()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("DATE");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isTemporal();
      assertEquals(true, boolean0);
  }

  @Test
  public void test18()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance("TIMESTAMP");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isTemporal();
      assertEquals(true, boolean0);
  }

  @Test
  public void test19()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isTemporal();
      assertEquals(false, boolean0);
      assertEquals(true, dBDataType0.isNumber());
  }

  @Test
  public void test20()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(1196, "TIME06CLOB");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.isTemporal();
      assertEquals(true, boolean0);
      assertEquals(true, dBDataType0.isNumber());
  }

  @Test
  public void test21()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.equals((Object) null);
      assertEquals(false, boolean0);
      assertEquals(false, dBDataType0.isAlpha());
  }

  @Test
  public void test22()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance((-1323), "TIME");
      assertNotNull(dBDataType0);
      
      DBDataType dBDataType1 = DBDataType.getInstance("TIME");
      assertNotNull(dBDataType1);
      
      boolean boolean0 = dBDataType0.equals((Object) dBDataType1);
      assertEquals(true, boolean0);
      assertEquals(-1323, dBDataType0.getJdbcType());
  }

  @Test
  public void test23()  throws Throwable  {
      DBDataType dBDataType0 = DBDataType.getInstance(0, "ik");
      assertNotNull(dBDataType0);
      
      boolean boolean0 = dBDataType0.equals((Object) "IK");
      assertEquals(false, boolean0);
      assertEquals(false, dBDataType0.isAlpha());
  }
}
