/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Date;
import java.util.List;
import org.databene.commons.ObjectNotFoundException;
import org.databene.commons.version.VersionNumber;
import org.databene.jdbacl.model.DBCatalog;
import org.databene.jdbacl.model.DBPackage;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBSequence;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DBTrigger;
import org.databene.jdbacl.model.Database;
import org.databene.jdbacl.model.DefaultDatabase;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDefaultDatabase {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("OI2trse+bB0<45.V{*", "OI2trse+bB0<45.V{*", (VersionNumber) null);
      defaultDatabase0.setImportedChecks(false);
      assertEquals(false, defaultDatabase0.isImportedChecks());
  }

  @Test
  public void test1()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      defaultDatabase0.setImportedUKs(false);
      assertEquals(false, defaultDatabase0.isImportedUKs());
  }

  @Test
  public void test2()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("2)", "2)", (VersionNumber) null);
      String string0 = defaultDatabase0.getUser();
      assertNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("2)", "2)", (VersionNumber) null);
      boolean boolean0 = defaultDatabase0.isImportedUKs();
      assertEquals(false, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("nc", "nc", (VersionNumber) null);
      DBCatalog dBCatalog0 = new DBCatalog("nc");
      defaultDatabase0.removeCatalog(dBCatalog0);
      assertEquals("nc", defaultDatabase0.getDatabaseProductName());
  }

  @Test
  public void test5()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      defaultDatabase0.setTableInclusionPattern((String) null);
      assertEquals(false, defaultDatabase0.isImportedIndexes());
  }

  @Test
  public void test6()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("-ygr-k%|6?@zUwWg/y7{", "-ygr-k%|6?@zUwWg/y7{", (VersionNumber) null);
      defaultDatabase0.setImportDate((Date) null);
      assertEquals(false, defaultDatabase0.isImportedUKs());
  }

  @Test
  public void test7()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("ZnYhH0hg", "ZnYhH0hg", (VersionNumber) null);
      VersionNumber versionNumber0 = defaultDatabase0.getDatabaseProductVersion();
      assertNull(versionNumber0);
  }

  @Test
  public void test8()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      defaultDatabase0.setTableExclusionPattern("7f@2[Emrre>U?W@R");
      assertEquals("database", defaultDatabase0.getObjectType());
  }

  @Test
  public void test9()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("2)", "2)", (VersionNumber) null);
      Date date0 = defaultDatabase0.getImportDate();
      assertNull(date0);
  }

  @Test
  public void test10()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("nc", "nc", (VersionNumber) null);
      // Undeclared exception!
      try {
        defaultDatabase0.getTable("nc");
        fail("Expecting exception: ObjectNotFoundException");
      } catch(ObjectNotFoundException e) {
        /*
         * Table 'nc'
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("sk&fOxePhH", "sk&fOxePhH", (VersionNumber) null);
      String string0 = defaultDatabase0.getTableExclusionPattern();
      assertNull(string0);
  }

  @Test
  public void test12()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("OI2trse+bB0<45.V{*", "OI2trse+bB0<45.V{*", (VersionNumber) null);
      boolean boolean0 = defaultDatabase0.isImportedSequences();
      assertEquals(false, boolean0);
  }

  @Test
  public void test13()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("nc", "nc", (VersionNumber) null);
      defaultDatabase0.setImportedSequences(true);
      assertEquals(true, defaultDatabase0.isImportedSequences());
  }

  @Test
  public void test14()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("nc", "nc", (VersionNumber) null);
      String string0 = defaultDatabase0.getDatabaseProductName();
      assertEquals("nc", string0);
  }

  @Test
  public void test15()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      boolean boolean0 = defaultDatabase0.isImportedIndexes();
      assertEquals(false, boolean0);
  }

  @Test
  public void test16()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("$$");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("$$", "$$", versionNumber0);
      List<DBSequence> list0 = defaultDatabase0.getSequences();
      assertEquals(true, list0.isEmpty());
  }

  @Test
  public void test17()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("$$");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("$$", "$$", versionNumber0);
      String string0 = defaultDatabase0.getTableInclusionPattern();
      assertNull(string0);
  }

  @Test
  public void test18()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("2)", "2)", (VersionNumber) null);
      DBCatalog dBCatalog0 = defaultDatabase0.getCatalog("2)");
      assertNull(dBCatalog0);
  }

  @Test
  public void test19()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("", "", (VersionNumber) null);
      DBCatalog dBCatalog0 = new DBCatalog("", (Database) defaultDatabase0);
      // Undeclared exception!
      try {
        defaultDatabase0.getSchema("");
        fail("Expecting exception: ObjectNotFoundException");
      } catch(ObjectNotFoundException e) {
        /*
         * Table ''
         */
      }
  }

  @Test
  public void test20()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("2)", "2)", (VersionNumber) null);
      defaultDatabase0.setUser("2)");
      assertNull(defaultDatabase0.getDoc());
  }

  @Test
  public void test21()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("-ygr-k%|6?@zUwWg/y7{", "-ygr-k%|6?@zUwWg/y7{", (VersionNumber) null);
      boolean boolean0 = defaultDatabase0.isImportedChecks();
      assertEquals(false, boolean0);
  }

  @Test
  public void test22()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("sk&fOxePhH", "sk&fOxePhH", (VersionNumber) null);
      defaultDatabase0.setImportedIndexes(false);
      assertEquals(false, defaultDatabase0.isImportedIndexes());
  }

  @Test
  public void test23()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("", "", (VersionNumber) null);
      // Undeclared exception!
      try {
        defaultDatabase0.getSchema("");
        fail("Expecting exception: ObjectNotFoundException");
      } catch(ObjectNotFoundException e) {
        /*
         * Table ''
         */
      }
  }

  @Test
  public void test24()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("SYSTEM_TR?GG5RS", "SYSTEM_TR?GG5RS", (VersionNumber) null);
      List<DBTable> list0 = defaultDatabase0.getTables(false);
      assertEquals(0, list0.size());
  }

  @Test
  public void test25()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("ZnYhH0hg", "ZnYhH0hg", (VersionNumber) null);
      DBCatalog dBCatalog0 = new DBCatalog("ZnYhH0hg", (Database) defaultDatabase0);
      List<DBTable> list0 = defaultDatabase0.getTables();
      assertEquals(0, list0.size());
  }

  @Test
  public void test26()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      DBCatalog dBCatalog0 = new DBCatalog("", (Database) defaultDatabase0);
      // Undeclared exception!
      try {
        defaultDatabase0.removeTable("7f@2[Emrre>U?W@R");
        fail("Expecting exception: ObjectNotFoundException");
      } catch(ObjectNotFoundException e) {
        /*
         * Table '7f@2[Emrre>U?W@R'
         */
      }
  }

  @Test
  public void test27()  throws Throwable  {
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("OI2trse+bB0<45.V{*", "OI2trse+bB0<45.V{*", (VersionNumber) null);
      DBTable dBTable0 = defaultDatabase0.getTable("OI2trse+bB0<45.V{*", false);
      assertNull(dBTable0);
  }

  @Test
  public void test28()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      List<DBSequence> list0 = defaultDatabase0.getSequences(false);
      assertEquals(true, list0.isEmpty());
  }

  @Test
  public void test29()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      DBCatalog dBCatalog0 = new DBCatalog("", (Database) defaultDatabase0);
      List<DBSequence> list0 = defaultDatabase0.getSequences(true);
      assertEquals(0, list0.size());
  }

  @Test
  public void test30()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      DBCatalog dBCatalog0 = new DBCatalog("", (Database) defaultDatabase0);
      DBSchema dBSchema0 = new DBSchema("7f@2[Emrre>U?W@R", dBCatalog0);
      List<DBTrigger> list0 = defaultDatabase0.getTriggers();
      assertEquals(0, list0.size());
  }

  @Test
  public void test31()  throws Throwable  {
      VersionNumber versionNumber0 = VersionNumber.valueOf("7f@2[Emrre>U?W@R");
      DefaultDatabase defaultDatabase0 = new DefaultDatabase("7f@2[Emrre>U?W@R", "7f@2[Emrre>U?W@R", versionNumber0);
      DBCatalog dBCatalog0 = new DBCatalog("", (Database) defaultDatabase0);
      DBSchema dBSchema0 = new DBSchema("7f@2[Emrre>U?W@R", dBCatalog0);
      List<DBPackage> list0 = defaultDatabase0.getPackages();
      assertEquals(0, list0.size());
  }
}
