/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.List;
import org.databene.jdbacl.model.ContainerComponent;
import org.databene.jdbacl.model.DBSchema;
import org.databene.jdbacl.model.DBSequence;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DefaultDBTable;
import org.databene.jdbacl.model.TableContainer;
import org.databene.jdbacl.model.TableContainerSupport;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTableContainerSupport {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TableContainer tableContainer0 = new TableContainer("`~b;y+bw&E3oVk'");
      DBTable dBTable0 = tableContainer0.getTable("avr");
      assertNull(dBTable0);
  }

  @Test
  public void test1()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      List<DBTable> list0 = tableContainerSupport0.getTables();
      assertEquals(true, list0.isEmpty());
  }

  @Test
  public void test2()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      List<ContainerComponent> list0 = tableContainerSupport0.getComponents();
      assertEquals(true, list0.isEmpty());
  }

  @Test
  public void test3()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      DBSequence dBSequence0 = new DBSequence("AGW", (DBSchema) null);
      tableContainerSupport0.addSequence(dBSequence0);
      assertEquals("AGW", dBSequence0.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      TableContainer tableContainer0 = new TableContainer("`~b;y+bw&E3oVk'");
      // Undeclared exception!
      try {
        tableContainer0.removeTable((DBTable) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      DefaultDBTable defaultDBTable0 = new DefaultDBTable("1=L9F,:");
      tableContainerSupport0.addTable((DBTable) defaultDBTable0);
      assertEquals(0, defaultDBTable0.countProviders());
  }

  @Test
  public void test6()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      TableContainer tableContainer0 = new TableContainer("1=L9F,:");
      tableContainerSupport0.addSubContainer(tableContainer0);
      List<DBTable> list0 = tableContainerSupport0.getTables(true);
      assertEquals(true, list0.isEmpty());
  }

  @Test
  public void test7()  throws Throwable  {
      TableContainerSupport tableContainerSupport0 = new TableContainerSupport();
      TableContainer tableContainer0 = new TableContainer("1=L9F,:");
      tableContainerSupport0.addSubContainer(tableContainer0);
      List<DBSequence> list0 = tableContainerSupport0.getSequences(true);
      assertEquals(true, list0.isEmpty());
  }
}
