/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.databene.jdbacl.model.DBNonUniqueIndex;
import org.databene.jdbacl.model.DBTable;
import org.databene.jdbacl.model.DefaultDBColumn;
import org.databene.jdbacl.model.DefaultDBTable;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestAbstractDBTableComponent {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultDBColumn defaultDBColumn0 = new DefaultDBColumn("", (DBTable) null, 741, "");
      DBTable dBTable0 = defaultDBColumn0.getTable();
      assertNull(dBTable0);
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultDBTable defaultDBTable0 = new DefaultDBTable("BINARY_DOUBLE");
      String[] stringArray0 = new String[7];
      DBNonUniqueIndex dBNonUniqueIndex0 = new DBNonUniqueIndex("BINARY_DOUBLE", true, (DBTable) defaultDBTable0, stringArray0);
      assertEquals("BINARY_DOUBLE", dBNonUniqueIndex0.getName());
  }
}
