/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.swing.JTextField;
import org.databene.jdbacl.swing.TextFieldValueProvider;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestTextFieldValueProvider {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      JTextField jTextField0 = new JTextField();
      TextFieldValueProvider textFieldValueProvider0 = new TextFieldValueProvider(jTextField0);
      String string0 = textFieldValueProvider0.getValue();
      assertEquals("", string0);
  }
}
