/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import javax.swing.JTextField;
import org.databene.commons.ConnectFailedException;
import org.databene.commons.ImportFailedException;
import org.databene.jdbacl.swing.DatabasePane;
import org.databene.jdbacl.swing.TextFieldValueProvider;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDatabasePane {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DatabasePane databasePane0 = new DatabasePane((TextFieldValueProvider) null);
      databasePane0.setEnvironment((String) null);
  }

  @Test
  public void test1()  throws Throwable  {
      TextFieldValueProvider textFieldValueProvider0 = new TextFieldValueProvider((JTextField) null);
      DatabasePane databasePane0 = new DatabasePane(textFieldValueProvider0);
      assertNotNull(databasePane0);
      
      DatabasePane.Importer databasePane_Importer0 = databasePane0.new Importer("0u6Jmli!N ");
      // Undeclared exception!
      try {
        databasePane_Importer0.run();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * org.databene.commons.ConfigurationError: No environment definition '0u6Jmli!N .env.properties' found
         */
      }
  }
}
